//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Asset
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        
        [DisplayName("Card Name")]

        public string CardName { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<decimal> Price { get; set; }
        
        [DisplayName("Creator")]

        public Nullable<int> CreatorId { get; set; }
        public Nullable<int> Year { get; set; }

        [DisplayName("Date Created")]

        public Nullable<System.DateTime> dateCreated { get; set; }
    
        public virtual Creator Creator { get; set; }
    }
}
